name: Gentx
on: [pull_request]
jobs:
  verify-gentx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: gentx-validation
        run: |
          make verify-gentx
      - name: gentx-verification-failed
        if: ${{ failure() }}
        uses: mshick/add-pr-comment@v1
        with:
          message: "Gentx verification failed"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
